// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdsaTracker.Data;

namespace pdsatracker.Migrations
{
    [DbContext(typeof(PdsaDbContext))]
    partial class PdsaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pdsatracker.Models.Pdsa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Doing")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gap")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Plan")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Shared")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Study")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Pdsas");
                });
#pragma warning restore 612, 618
        }
    }
}
